hhhh

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -14,12 +14,19 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Set up Go
-      uses: actions/setup-go@v2
+      uses: actions/setup-go@v1
       with:
         go-version: '^1.16'
 
+    - name: Check for Go script
+      run: |
+        if [ ! -f main.go ]; then
+          echo "Go script not found. Failing the workflow."
+          exit 1
+        fi
+
     - name: Run Go script
-      run: go run ./that.go
+      run: go run that.go
 
     - name: Retrieve commits.txt
       run: cat commits.txt
